[build]
    command = "npm run build && rm -rf node_modules && cd .netlify/functions && npm install"
    functions = ".netlify/functions"
    publish = "dist/"

[functions]
    node_bundler = "esbuild"
